[package]
name = "part3_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]

cortex-m = "0.7.4"
cortex-m-rt = "0.6.10"
stm32f4 = {version = "0.8.0", features = ["stm32f411", "rt"]}
nb = "0.1.2"
alloc-cortex-m = "0.4.2"
panic-halt = "0.2.0"

